### ISSUE TITLE
Edit/Delete Posts

### ISSUE THREAD

**Issue by deckiedevs** [Clu-Codes/something-special#14]
## Description
- Currently, the edit post page does not allow the user to fully edit their post.
- Additionally, when viewing the edit post page, it is unclear which post is being edited.
- Submitting post revisions does not seem to update the post.
- Image preview gets stretched if it isn't the same aspect ratio.  (Issue #15)
<img src="https://i.imgur.com/RyPfMB8.png" width="500">

## To Do
- Fix edit post submission function.
- Add functionality to edit price.
- Add functionality to edit category.
- Add functionality to delete post.
- Add preview of current post, before any revisions are made, so that the user can tell which post they are editing.
- Fix image preview of uploaded post so that does not get stretched.

## Extra
- Time permitting, write logic to ensure that users can only edit posts they have authored.

**Comment by Clu-Codes** [comment]
Finished edit page. Working on delete now.

**Comment by Clu-Codes** [comment]
Finished delete logic.
