### ISSUE TITLE
Image Sizing

### ISSUE THREAD

**Issue by deckiedevs** [Clu-Codes/something-special#15]
## Description
* Uploading large images on the dashboard causes the image to overflow out of the container.
* On the edit post page, uploaded images get stretched and distorted to fit the width of the image preview. (Issue #14)
* Images of different sizes causes the posting's card to render as different sizes.

<img src="https://i.imgur.com/fJJuGQZ.png" width="500">
<img src="https://i.imgur.com/RyPfMB8.png" width="500">
<img src="https://i.imgur.com/Kkuyrfr.png" width="500">

## To Do
- ~~Fix dashboard image preview to fit container element.~~
- Fix edit post image preview to cover preview size without stretching the image.
- ~~Create uniform card image sizes.~~

**Comment by deckiedevs** [comment]
I've fixed two out of three of these!  Dashboard image preview and card images should be good to go now.  The edit post image preview still needs to be fixed, along with the other issues in the edit posts page (#14).

**Comment by Clu-Codes** [comment]
Fixed edit post image preview image issue.
